name: 'S.Lay Sculpin Site'
locale: en

menu_links:
    -
        title: Home
        url: /
    -
        title: About Me
        url: /about-me
    -
        title: About Work
        url: /about-work
    -
        title: Hobbies and Interests
        url: /interests
    -
        title: University Projects
        url: /uni-projects
        
proseClasses: 
    prose prose-p:text-base prose-p:text-dark-blue prose-headings:font-medium prose-h2:text-2xl/snug prose-a:font-medium prose-a:underline prose-li:marker:text-purple-blue hover:prose-a:text-purple-blue

